<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	    <IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>
	</PropertyGroup>
	
	<ItemGroup>
		<Folder Include="Protos\" />
	</ItemGroup>
	
    <ItemGroup>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Google.Api.CommonProtos" />
        <PackageReference Include="Grpc.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>		
	</ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\users.proto" GrpcServices="Server" />
    </ItemGroup>
</Project>
