services:
  uiservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uiservice
    ports:
      - "5129:5129"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5129
      - ApiUrls__Topics=http://topics-service:5294
      - ApiUrls__Auth=http://auth-users-service:5225
      - ApiUrls__Comments=http://comments-service:5044
    networks:
      - otus-network

networks:
  otus-network:
    external: true
