syntax = "proto3";

option csharp_namespace = "OtusForum.CommentsService.Grpc";

import "google/api/annotations.proto";

package comments;

service CommentsGrpcApi {
	rpc GetCommentsByTopic (GetCommentsByTopicRequest) returns (GetCommentsByTopicResponse) {
		option (google.api.http) = {
	    	post: "/api/v1/comments/bytopic"
	    	body: "*"
		};
	}
}

message GetCommentsByTopicRequest {
	int64 topic_id = 1;
}

message GetCommentsByTopicResponse {
	repeated Comment comments = 1;
}

message Comment {
	int64 id = 1;
	int64 topic_id = 2;
	int64 parent_comment_id = 3;
	int64 author_id = 4;
	string content = 5;
	string created_at = 6;
	string updated_at = 7;
}
