<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="FluentValidation" Version="12.1.1" />
        <PackageVersion Include="MediatR" Version="14.2.0" />
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
		<PackageVersion Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="10.0.10" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
        <PackageVersion Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
		<PackageVersion Include="Google.Protobuf" Version="3.35.1" />
		<PackageVersion Include="Grpc.Net.Client" Version="2.83.0" />
		<PackageVersion Include="Grpc.Tools" Version="2.83.0" />
		<PackageVersion Include="Google.Api.CommonProtos" Version="2.17.0" />
    </ItemGroup>
</Project>